apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deployment
  namespace: automation
  labels:
    app: ansible
spec:
  selector:
    matchLabels:
      app: ansible
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
      - name: ansible
        image: 10.31.200.3:32000/ansible
        args:
          - pwd
          - ls
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
